source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'
gem 'rails-api'
gem 'sqlite3'
gem 'thin'
gem 'active_model_serializers'
gem 'rack-cors', :require => 'rack/cors'
gem 'bcrypt-ruby', '~> 3.0.0'
